# Generated by Django 3.2 on 2021-05-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('transaction_type', models.BooleanField()),
                ('transaction_date', models.DateTimeField(verbose_name='transaction date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfersender_account', to='main.account')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferreceiver_account', to='main.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions_history',
        ),
    ]
