# Generated by Django 3.2 on 2021-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210528_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
